spring:
  # H2 데이터베이스에 연결 정보와 맞게 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 애플리케이션 로딩 시점에 테이블 DROP 후 다시 생성 애플리케이션 내려가도 DB를 남겨놓음 -> DB 확인가능 (단, 실제 운영에선 사용 x 공부 목적으로만)
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
        format_sql: true

logging.level:
  # JPA 실행 쿼리를 로그로 남겨놓을 수 있음 -> 위의 show_sql은 콘솔에 보여지는건데, 그것보단 로그로 남겨놓는 것이 좋음
  org.hibernate.SQL: debug
  # 파라미터 까지 볼 수 있는 옵션 (보기에 좀 불편 하므로 외부 라이브러리 사용 -> 운영에서는 성능저하가 있을 수 있기 때문에 필히 성능 테스트 후 도입)
  #org.hibernate.type: trace